DROP TABLE IF EXISTS cache_locks;
DROP TABLE IF EXISTS cache;
CREATE TABLE cache (`key` VARCHAR(255) NOT NULL PRIMARY KEY, value MEDIUMTEXT NOT NULL, expiration INT NOT NULL);
CREATE TABLE cache_locks (`key` VARCHAR(255) NOT NULL PRIMARY KEY, owner VARCHAR(255) NOT NULL, expiration INT NOT NULL);
